FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    curl \
    git \
    jq \
    khal \
    python3 \
    ripgrep \
    vdirsyncer \
  && rm -rf /var/lib/apt/lists/*

CMD ["sleep", "infinity"]
