version: "3"

tasks:
  disk:
    desc: Check disk space
    cmds:
      - df -h
    
  memory:
    desc: Check memory usage
    cmds:
      - free -h

  models:list:
    desc: List available models
    cmds:
      - pnpm openclaw models list

  models:list:anthropic:
    desc: List Anthropic models only
    cmds:
      - pnpm openclaw models list | grep anthropic

  models:current:
    desc: Show current default model
    cmds:
      - pnpm openclaw config get agents.defaults.model.primary 2>/dev/null || echo "(not set - using provider default)"

  config:agents:
    desc: Show full agents config section
    cmds:
      - pnpm openclaw config get agents

  status:
    desc: Show gateway status including active model
    cmds:
      - pnpm openclaw status

  models:set:sonnet:
    desc: Set model to Claude Sonnet 4.5
    cmds:
      - pnpm openclaw models set anthropic/claude-sonnet-4-5

  models:set:opus:
    desc: Set model to Claude Opus 4.5
    cmds:
      - pnpm openclaw models set anthropic/claude-opus-4-5

  models:set:kimi:
    desc: Set model to Kimi K2.5 via OpenRouter
    cmds:
      - pnpm openclaw models set openrouter/moonshotai/kimi-k2.5

  models:set:kimi-fw:
    desc: Set model to Kimi K2.5 via Fireworks (direct)
    cmds:
      - pnpm openclaw models set fireworks/accounts/fireworks/models/kimi-k2p5

  restart:
    desc: Restart the gateway
    cmds:
      - tmux kill-session -t gateway 2>/dev/null || true
      - sleep 2
      - tmux new -s gateway -d 'pnpm openclaw gateway --tailscale serve 2>&1 | tee ~/.openclaw/gateway.log'

  logs:
    desc: Follow gateway logs
    cmds:
      - tail -f ~/.openclaw/gateway.log

  tmux:attach:
    desc: Attach to the tmux session
    cmds:
      - tmux attach -t gateway
    
  cron:list:
    desc: List cron jobs
    cmds:
      - pnpm openclaw cron list

  containers:
    desc: List containers
    cmds:
      - docker ps
